/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alejandrov.frontend;

import com.alejandrov.backend.Mapa;
import com.alejandrov.backend.listas.Lista;
import com.alejandrov.frontend.componentes.Cuadro;
import com.alejandrov.frontend.planetas.Planeta;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.Border;

/**
 * @author aleja
 */
public class KonquestFrame extends javax.swing.JFrame {


    final private int ALTURA_MAIN;
    public JPanel cuadricula;
    public Cuadro[][] cuadros;

    public KonquestFrame() {

        initComponents();

        setLocationRelativeTo(null);
        ALTURA_MAIN = Center.getHeight()-10;
        Messages.setVisible(false);
    }

    public void crearCuadricula(Mapa mapa) {
        int columnas = mapa.getColumnas();
        int filas = mapa.getFilas();
        cuadricula = new JPanel(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();

        Border lineaNegra = BorderFactory.createLineBorder(new Color(40, 40, 40, 255),1);
        cuadricula.setBorder(lineaNegra);
        cuadricula.setBackground(new Color(156, 156, 156, 180));

        int ladoCuadro = (int) Math.floor(ALTURA_MAIN / filas);

        cuadricula.setMinimumSize(new Dimension(ladoCuadro * columnas, ladoCuadro * filas));
        cuadricula.setMaximumSize(new Dimension(ladoCuadro * columnas, ladoCuadro * filas));

        cuadros = new Cuadro[columnas][filas];

        for (int i = 0; i < columnas; i++) {
            for (int j = 0; j < filas; j++) {
                Cuadro cuadro = new Cuadro();
                cuadros[i][j] = cuadro;

                cuadro.setPreferredSize(new Dimension(ladoCuadro, ladoCuadro));
                cuadro.setBorder(lineaNegra);
                c.fill = GridBagConstraints.BOTH;
                c.gridx = i;
                c.gridy = j;
                cuadricula.add(cuadro, c);
            }
        }

        Center.add(cuadricula);
    }

    public JPanel getMessages() {
        return Messages;
    }

    public JPanel getCenter() {
        return Center;
    }

    public Cuadro[][] getCuadros() {
        return cuadros;
    }

    public JPanel getCuadricula() {
        return cuadricula;
    }

    public void setFondo(ImageIcon icon) {
        fondoLabel.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        North = new javax.swing.JPanel();
        menuAcciones = new javax.swing.JPanel();
        nuevoButton = new javax.swing.JButton();
        terminarJuegoButton = new javax.swing.JButton();
        terminarTurno = new javax.swing.JButton();
        calcularDistanciaButton = new javax.swing.JButton();
        consultaFlotaButton = new javax.swing.JButton();
        menuInstrucciones = new javax.swing.JPanel();
        instruccionLabel = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        navesMandarLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        terminarTurnoButton = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        Messages = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MensajesList = new javax.swing.JList<>();
        fondoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konquest");
        setMaximumSize(new java.awt.Dimension(1100, 680));
        setMinimumSize(new java.awt.Dimension(1100, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        North.setPreferredSize(new java.awt.Dimension(1100, 80));
        North.setLayout(new javax.swing.BoxLayout(North, javax.swing.BoxLayout.Y_AXIS));

        menuAcciones.setPreferredSize(new java.awt.Dimension(1100, 38));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        menuAcciones.setLayout(flowLayout1);

        nuevoButton.setText("Nuevo");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });
        menuAcciones.add(nuevoButton);

        terminarJuegoButton.setText("Terminar Juego");
        terminarJuegoButton.setEnabled(false);
        menuAcciones.add(terminarJuegoButton);

        terminarTurno.setText("Terminar turno");
        terminarTurno.setEnabled(false);
        menuAcciones.add(terminarTurno);

        calcularDistanciaButton.setText("Calcular distancia");
        calcularDistanciaButton.setEnabled(false);
        menuAcciones.add(calcularDistanciaButton);

        consultaFlotaButton.setText("Consulta de flota");
        consultaFlotaButton.setEnabled(false);
        menuAcciones.add(consultaFlotaButton);

        North.add(menuAcciones);

        menuInstrucciones.setBackground(new java.awt.Color(167, 167, 167));
        menuInstrucciones.setPreferredSize(new java.awt.Dimension(1100, 42));
        menuInstrucciones.setLayout(new java.awt.BorderLayout());
        menuInstrucciones.add(instruccionLabel, java.awt.BorderLayout.LINE_START);

        Right.setBackground(new java.awt.Color(167, 167, 167));
        Right.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        navesMandarLabel.setText("Naves a mandar:");
        Right.add(navesMandarLabel);

        jTextField1.setEnabled(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(60, 28));
        Right.add(jTextField1);

        terminarTurnoButton.setText("Terminar turno");
        terminarTurnoButton.setEnabled(false);
        Right.add(terminarTurnoButton);

        menuInstrucciones.add(Right, java.awt.BorderLayout.LINE_END);

        North.add(menuInstrucciones);

        getContentPane().add(North, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Center.setBorder(null);
        Center.setOpaque(false);
        Center.setPreferredSize(new java.awt.Dimension(1100, 400));
        getContentPane().add(Center, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        Messages.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensajes"));
        Messages.setPreferredSize(new java.awt.Dimension(1100, 200));

        MensajesList.setBackground(new java.awt.Color(51, 51, 51));
        MensajesList.setForeground(new java.awt.Color(199, 199, 199));
        jScrollPane1.setViewportView(MensajesList);

        javax.swing.GroupLayout MessagesLayout = new javax.swing.GroupLayout(Messages);
        Messages.setLayout(MessagesLayout);
        MessagesLayout.setHorizontalGroup(
            MessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
        );
        MessagesLayout.setVerticalGroup(
            MessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        getContentPane().add(Messages, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        fondoLabel.setOpaque(true);
        fondoLabel.setPreferredSize(new java.awt.Dimension(1100, 680));
        getContentPane().add(fondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed
        MapaDesignFrame mapaDesign = new MapaDesignFrame(this);
        mapaDesign.setLocationRelativeTo(this);
        mapaDesign.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_nuevoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center;
    private javax.swing.JList<String> MensajesList;
    private javax.swing.JPanel Messages;
    private javax.swing.JPanel North;
    private javax.swing.JPanel Right;
    private javax.swing.JButton calcularDistanciaButton;
    private javax.swing.JButton consultaFlotaButton;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JLabel instruccionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel menuAcciones;
    private javax.swing.JPanel menuInstrucciones;
    private javax.swing.JLabel navesMandarLabel;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JButton terminarJuegoButton;
    private javax.swing.JButton terminarTurno;
    private javax.swing.JButton terminarTurnoButton;
    // End of variables declaration//GEN-END:variables
}
